### ISSUE TITLE
Request: WiFi Direct and VoLTE icon support

### ISSUE THREAD

**Issue by rustyshelf** [zacharee/SystemUITuner2#1]
I came across your app in the Google Play Store while trying to clean up some icons on my Samsung status bar. You have all the standard ones which is great, but two that I'd love to figure out the names of are the WiFi Direct and VoLTE icons. I've been trying all sorts of name combinations but I haven't been able to find one that works...
`adb shell settings put secure icon_blacklist ...`

Anyway if you have anyway of finding out what these are called I'd be super grateful. If you don't no worries. Sorry for posting this here, didn't know where else to put it.

**Comment by zacharee** [comment]
Join the Telegram chat so we can discuss what you've tried.

Sent from Alto
On Thursday, April 20, 2017 at 6:59 AM rustyshelf <notifications@github.com> wrote:

I came across your app in the Google Play Store while trying to clean up some icons on my Samsung status bar. You have all the standard ones which is great, but two that I'd love to figure out the names of are the WiFi Direct and VoLTE icons. I've been trying all sorts of name combinations but I haven't been able to find one that works...
adb shell settings put secure icon_blacklist ...

Anyway if you have anyway of finding out what these are called I'd be super grateful. If you don't no worries. Sorry for posting this here, didn't know where else to put it.

**Comment by rustyshelf** [comment]
Happy to but I can't find any reference to a Telegram chat?

**Comment by zacharee** [comment]
Check the XDA thread.

Sent from Alto
On Thursday, April 20, 2017 at 7:05 AM rustyshelf <notifications@github.com> wrote:

Happy to but I can't find any reference to a Telegram chat?
